import streamlit as st
import os
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.document_loaders import PyPDFLoader, TextLoader, Docx2txtLoader, UnstructuredPowerPointLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
import tempfile

# ^ all necessary imports for the Streamlit app, including libraries for handling environment variables, document loading, text splitting, vector storage, and the RAG chain components

load_dotenv()
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

# session state initialization to store vectorstore, chat history, and RAG chain across user interactions
# initialize session state variables
if "vectorstore" not in st.session_state:  # vectorstore will hold the indexed documents for retrieval
    st.session_state.vectorstore = None  # initialized to None until user uploads documents and they are processed

if "chat_history" not in st.session_state:   # chat_history will store the conversation history between the user and the assistant
    st.session_state.chat_history = []   # initialized as an empty list to store the sequence of messages in the chat

if "rag_chain" not in st.session_state: # rag_chain will hold the Retrieval-Augmented Generation chain that processes user queries and retrieves relevant information from the vectorstore
    st.session_state.rag_chain = None  # initialized to None until the RAG chain is created based on the uploaded documents and vectorstore

def process_uploaded_file(uploaded_file, content_type): # function to process the uploaded file, extract its content, and prepare it for indexing in the vectorstore
    # save uploaded file temporarily to disk
    with tempfile.NamedTemporaryFile(delete=False, suffix=os.path.splitext(uploaded_file.name)[1]) as f: # creates a temporary file on disk with the same extension as the uploaded file, 
        # which will be used to store the uploaded content for processing
        f.write(uploaded_file.getvalue()) # writes the content of the uploaded file to the temporary file, allowing it to be processed by the appropriate loader
        # based on its type (PDF, DOCX, TXT)
        temp_path = f.name # stores the path to the temporary file, 
        # which will be used to load the document content using the appropriate loader based on the file extension

    # pick the right loader
    ext = os.path.splitext(uploaded_file.name)[1].lower() # extracts the file extension from the uploaded file's name 
    # and converts it to lowercase to determine which loader to use for processing the document content
    loaders = {
        ".pdf": PyPDFLoader, 
        ".docx": Docx2txtLoader, 
        ".txt": TextLoader,
        ".pptx": UnstructuredPowerPointLoader
    } #  dictionary mapping file extensions to their corresponding document loader 
    # classes, which will be used to load the content of the uploaded file based on its type
    loader = loaders[ext](temp_path) # 
    docs = loader.load() # loads the content of the temporary file using the appropriate loader based on its extension,

    # tag each chunk with content type
    for doc in docs:  # loop through each document chunk that was loaded from the uploaded file and adds metadata to indicate the content type and source of the document, which will be useful for retrieval and response generation in the RAG chain
        doc.metadata["content_type"] = content_type   # adds a metadata field to each document chunk indicating the type of content (e.g., lecture notes, textbooks, lab manuals, past papers) based on the user's selection in the sidebar, which can be used for filtering and retrieval in the RAG chain
        doc.metadata["source"] = uploaded_file.name    # adds a metadata field to each document chunk indicating the source of the document (the name of the uploaded file), which can be useful for tracking where the information came from when it is retrieved and used in responses generated by the RAG chain

    return docs   # returns the list of document chunks that have been processed and tagged with metadata, which will be used for indexing in the vectorstore and retrieval in the RAG chain

st.title("Academic Assistant") # sets the title of the Streamlit app to "Academic Assistant"

# Sidebar for file uploads
with st.sidebar:
    st.header("Upload Documents: ") # creates a header in the sidebar section of the Streamlit app to indicate that this area is for uploading academic documents, which will be processed and used by the assistant to answer questions based on the content of those documents
    uploaded_file = st.file_uploader("Upload your academic docs here", type=["pdf", "docx", "txt", "pptx"])    
    content_type = st.selectbox("Select content type:", ["Lecture Notes", "Textbook", "Lab Manual", "Past Paper"])  # creates a dropdown select box in the sidebar that allows users to specify the type of content they are uploading (e.g., lecture notes, textbooks, lab manuals, past papers), which will be used as metadata for the uploaded documents and can help the assistant provide more contextually relevant responses based on the type of content being queried
    
    if st.button("Process Document"): # creates a button in the sidebar that, when clicked, triggers the processing of the uploaded document, including loading its content, splitting it into chunks, indexing it in the vectorstore, and creating or updating the RAG chain for answering questions based on the uploaded content
        if uploaded_file is None:   # checks if the user has uploaded a file before attempting to process it, and if not, displays a warning message prompting the user to upload a file first, ensuring that the processing logic is only executed when there is an actual file to work with
            st.warning("Please upload a file first!")
        else: # if a file has been uploaded, the processing logic is executed, which includes loading the document content, splitting it into chunks, indexing it in the vectorstore, and creating or updating the RAG chain for answering questions based on the uploaded content. A spinner is displayed during processing to indicate that work is being done, and a success message is shown once processing is complete.
            with st.spinner("Processing..."):
                # process the file
                docs = process_uploaded_file(uploaded_file, content_type)  # calls the function to process the uploaded file, which loads its content, splits it into chunks, and tags it with metadata based on the selected content type, returning a list of document chunks that are ready for indexing in the vectorstore and retrieval in the RAG chain
                
                # split into chunks
                splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
                chunks = splitter.split_documents(docs)
                
                # create or update vector store
                embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")   # initializes the HuggingFaceEmbeddings class with the specified model name, which will be used to generate vector embeddings for the document chunks, allowing them to be indexed and retrieved based on their semantic content in the RAG chain
                if st.session_state.vectorstore is None:   #  checks if the vectorstore has already been initialized in the session state, and if not, creates a new FAISS vectorstore from the document chunks and their corresponding embeddings, which will be used for efficient retrieval of relevant information based on user queries in the RAG chain. If the vectorstore already exists, it adds the new document chunks to the existing vectorstore, allowing for incremental updates as more documents are uploaded and processed.
                    st.session_state.vectorstore = FAISS.from_documents(chunks, embeddings)     
                    # creates a new FAISS vectorstore from the document chunks and their corresponding embeddings if the vectorstore has not been initialized yet, allowing for efficient retrieval of relevant information based on user queries in the RAG chain
                else:
                    st.session_state.vectorstore.add_documents(chunks) # otherwise it adds the new document chunks to the existing vectorstore if it has already been initialized, allowing for incremental updates to the vectorstore as more documents are uploaded and processed, ensuring that all relevant information from the uploaded documents is available for retrieval in the RAG chain when answering user queries.
                
                # create RAG chain
                llm = ChatGroq(model="llama-3.1-8b-instant", api_key=GROQ_API_KEY, temperature=0.3)
                prompt = ChatPromptTemplate.from_template("""
Role: Expert Academic Assistant.
Task: Synthesize answers from provided context.
Guidelines:
1. Combine theory with practicals and exam context.
2. Structure using headings for Concept, Examples, Exam Application.
3. Tag info with source type e.g. [Notes] or [Textbook].
4. If info is missing, state: "Context lacks [topic] details"
Context: {context}
Question: {question}
Answer:""")
                
                def format_docs(docs):
                    return "\n\n".join(f"[{doc.metadata.get('content_type', 'Unknown')}] {doc.page_content}" for doc in docs) 
                    # defines a function to format the retrieved documents for input into the RAG chain, which takes a list of document chunks and returns a formatted string that includes the content type as a tag (e.g., [Lecture Notes], [Textbook]) followed by the actual content of each document chunk, allowing the RAG chain to understand the source of the information when synthesizing answers to user questions based on the retrieved context.
                
                retriever = st.session_state.vectorstore.as_retriever(search_kwargs={"k": 3}) # creates a retriever from the vectorstore that will be used in the RAG chain to retrieve relevant document chunks based on user queries, with a search parameter of "k" set to 3, meaning that the retriever will return the top 3 most relevant document chunks for each query, providing sufficient context for the RAG chain to generate informed and accurate responses to user questions.
                st.session_state.rag_chain = ( # creates the RAG chain by combining the retriever, a formatting function for the retrieved documents, the defined prompt template, the language model (LLM), and an output parser. The RAG chain will take user questions as input, retrieve relevant document chunks from the vectorstore, format them for context, and use the LLM to generate structured answers based on the provided guidelines in the prompt template.
                    {"context": retriever | format_docs, "question": RunnablePassthrough()}  # defines the input structure for the RAG chain, where "context" is generated by retrieving relevant documents and formatting them, and "question" is passed through directly from the user's input without modification
                    | prompt
                    | llm
                    | StrOutputParser()
                ) # creates the RAG chain by combining the retriever, a formatting function for the retrieved documents, the defined prompt template, the language model (LLM), and an output parser. The RAG chain will take user questions as input, retrieve relevant document chunks from the vectorstore, format them for context, and use the LLM to generate structured answers based on the provided guidelines in the prompt template.
                
                st.success(f"[✓] {uploaded_file.name} processed as [{content_type}]!") # displays a success message in the Streamlit app indicating that the uploaded file has been successfully processed and indexed in the vectorstore, along with the content type that was selected for the document, providing feedback to the user that their document is now ready for querying through the chat interface.

    # show uploaded docs
    if st.session_state.vectorstore is not None:  # if the vector state has been initialized
        # i.e. atleast 1 document has been uploaded & processed, 
        # it retrieves the total number of documents currently indexed in the vectorstore
        # and displays this information in the sidebar, 
        # giving the user an indication of how many document chunks are available for retrieval 
        # and answering questions based on the uploaded content.
        st.info("Documents are ready! Ask a question.") # displays a message indicating docs are processed

# Main area for chat
st.header("Ask a Question")
# chat interface goes here

# display chat history
for message in st.session_state.chat_history:
    with st.chat_message(message["role"]):
        st.write(message["content"])

# initial greeting if no history
if not st.session_state.chat_history:
    with st.chat_message("assistant"):
        st.write("Hello! Upload your documents and ask me anything about them!")

# handle user input
user_input = st.chat_input("Ask a question...") # creates a chat input widget where the user can type their questions or queries
if user_input:
    # if user enters an input message
    # add user message to history
    st.session_state.chat_history.append({"role": "user", "content": user_input}) # add the message to chat history
    with st.chat_message("user"): # display user's input as a chat message
        st.write(user_input) # write user's input into the chat interface

    # generate response
    if st.session_state.rag_chain is None: # if ragchain hasnt been created yet
        with st.chat_message("assistant"): # assistant prompts user to upload and process a document first before asking questions
            st.write("Please upload and process a document first!")
        st.session_state.chat_history.append({"role": "assistant", "content": "Please upload and process a document first!"}) # add message to chat history
    else:
        with st.chat_message("assistant"):  # loading messages and stuff
            with st.spinner("Thinking..."): # to be displayed while loading
                answer = st.session_state.rag_chain.invoke(user_input) # generate a response for the input from user
                st.write(answer) # write the generated answer into the chat interface
        st.session_state.chat_history.append({"role": "assistant", "content": answer}) # add the generated answer to the chat history

